# Note: In a yml each level is padded by 2 spaces
name: Flutter

on:
 # Runs this action when you push on master
 push:
   branches: [ "master" ]
 # Runs this when a PR against master is created
 pull_request:
   branches: [ "master" ]

jobs:
  flutter_test:
    runs-on: ubuntu-latest
    # timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.47.2'

    - name: Flutter Doctor
      run: flutter doctor -v

    - name: Flutter Analyze
      run: flutter analyze

    - name: Flutter Format Check
      run: dart format --output=none --set-exit-if-changed .

    - name: Flutter Tests
      run: flutter test

    - name: Flutter Build Web
      run: flutter build web --release 
          --dart-define=apiKey=${{ secrets.FIREBASE_API_KEY }} 
          --dart-define=appId=${{ secrets.FIREBASE_APP_ID }} 
          --dart-define=messagingSenderId=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} 
          --dart-define=projectId=${{ secrets.FIREBASE_PROJECT_ID }} 
          --dart-define=authDomain=${{ secrets.FIREBASE_AUTH_DOMAIN }} 
          --dart-define=storageBucket=${{ secrets.FIREBASE_STORAGE_BUCKET }}

    # Step 5: Deploy to Firebase Hosting
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live # 'live' deploys directly to your production URL
        projectId: validacao-f840d # Replace with your Firebase Project ID
